metno/mmd

xslt/mmd-to-datacite.xsl
Mapping Publisher to dataset_citation/dataset_publisher and PublicationYear to dataset_citation/dataset_release_date
=> map Publisher and PublicationYear

doc/ch02-md-elements-personnel.adoc
Following discussions in #23 the specification for the personnel element is modified. Lara, can you please review and approve if agreeing?
=> Modifications following discussion in issue #23

xsd/mmd.xsd
=> start_date, end_date types to dateTime

src/createMETUUID.py, xsd/mmd.xsd
=> more generic and python3 print statements

doc/ch02-md-elements-dataset_production_status.adoc, doc/ch04-md-contrvocabs.adoc
=> #54: changed name of controlled vocabulary from  to

xsd/mmd.xsd
I'll merge #61, after this is merged.
=> add attribute to alternate_identifier

input-examples/sios-mdf.xml, xslt/mdform-to-mmd.xsl
modify xslt from metatdata form (sios) to mmd to support translation of multiple iso_topic_category
=> fix of mdform-to-mmd.xsl

bin/sentinel1_mmd_to_csw_iso19139.py
This only affects one file for translation from MMD to ISO19139. It will be replaced by new code in https://github.com/metno/py-mmd-tools but it will be good to merge and delete this branch.
=> Hotfix97 bug in executable

README.md
Link to the latest version of the html specification doc added to README.md
=> #94: added link to html preview of the latest version in master

.github/workflows/make-doc.yml, doc/ch01-introduction.adoc
This is a PR to check and try to get rid of the conflicts in the doc files on every PR. See #108.
=> Issue108 get rid of pr conflicts

xslt/mmdv2-to-mmdv3.xsl
The translation of data center contact to personnel contact was missing.
=> add translation of data center contact

bin/nc_to_mmd, mmd_utils/nc_to_mmd.py
Added command line options to decide whether services are processed or not and if WMS is present whether or not to include WMS-layers.
=> Modified to support selective processing of services.

doc/ch02-md-elements-platform.adoc, doc/ch04-md-contrvocabs.adoc, input-examples/foo.xml, input-examples/sentinel-1-mmd.xml, xslt/mmdv2-to-mmdv3.xsl
Changes in oscar links. The html and pdf are not updated. Are they not automatically generated by Actions?
=> change oscar links in documentation, examples, and xslt translation

xslt/mmd-to-iso.xsl
Fixes to mmd-to-iso mapping including:
1. add mmd prefix to address info
2. add keywords and keywords thesauri
3. add dataset landing page template
4. extract latest metadata_update datetime into dateStamp
5. data_access mapping protocol to osgeo.
6. add data center mapping 
7. restructure MD_LegalConstraints
=> Mmd iso fix

xsd/mmd.xsd, xslt/dif-to-mmd.xsl, xslt/mm2-to-mmd.xsl, xslt/mmdv2-to-mmdv3.xsl
Remove namespace of attribute relation_type
=> Relation type

doc/ch04-md-contrvocabs.adoc
Added product types as requested in #147
=> add product type S2MSI1C and S2MSI2A to controlled vocabulary

tests/test_schemas.py, xsd/mmd.xsd
This should solve #153 - I also added a test for future changes.
=> Issue153 xsd bug

doc/ch02-md-elements-data_center.adoc
=> #154: set repetition allowed to 'No'

xsd/mmd_strict.xsd
=> add access constraints vocabulary in schema

Dockerfile.unittests, tests/test_schemas.py, xslt/mmd-to-dcatap.xsl
=> first draft of mmd to dcat-ap for dataset

doc/ch04-md-contrvocabs.adoc, tests/test_schemas.py, xslt/mmd-to-geonorge.xslt
=> Issue164 dead link

xslt/mmd-to-dif.xsl
This PR updates the mmd-to-dif (9.8.4) transation to be compliant with mmd v3. It closes #171
=> update mmd-to-dif translation to comply with mmd version3

xslt/dcat-to-mmd.xsl
A first draft of dcat-to-mmd to map the Dataset class. Several issues are still open and would need further development:
- license is only present for the distribution class, not for dataset
- language can be multiple values
- distribution protocol is probably not straightforward to get from dcat.
=> add first draft of dcat-to-mmd

xsd/mmd.xsd, xslt/mmd-to-iso2.xsl, xslt/mmdv2-to-mmdv3.xsl
update mmd-to-iso2, mmdv2-to-mmdv3 and add Original record to mmd schema for last_metadata_update type
=> update translation to iso2, v2 to v3 and last metadata type vocab

xslt/mmd-to-inspire.xslt
This adds to the repository a translation to inspireEU
=> mmd translation to inspireEU

doc/ch02-md-elements-storage_information.adoc, doc/ch04-md-contrvocabs.adoc, input-examples/foo.xml, thesauri/mmd-vocabulary.ttl, thesauri/mmd-vocabulary.xml
This PR is updating the urls to the new GCMD service endpoint. Closes #188
=> update urls for GCMD Keyword Management Service to the new endpoint

xslt/mmd-to-wmo.xslt
This is a consolidated draft that can be merged for now. The mapping is not fully compliant with WMO Core Profile due to the fileidentifier pattern and the GTS Priority lacking for the legal constraints. "WMOCAT" vocabulary in MMD can be used to provide WMO keywords. Closes #169
=> Wmo profile

tests/data/precipitation_amount_st_92350.xml, tests/data/precipitation_amount_st_92350_EMPTY_ATTR.xml, tests/data/precipitation_amount_st_92350_NO_LANG_ATTR.xml, tests/test_schemas.py, xsd/mmd_strict.xsd
@ferrighi - can you have a look? I'm not sure if we need to do anything in mmd.xsd as well. I guess we should, but there seems to be other issues as well. And should we also test other attributes?
=> Issue185 invalid attributes

doc/ch04-md-contrvocabs.adoc, thesauri/mmd-vocabulary.ttl, thesauri/mmd-vocabulary.xml
Added instruments to vocabulary and documentation. Closes #195
=> add AVHRR and SSM/I instruments to vocabulary list

xslt/iso-to-mmd.xsl
The CMEMS CSW implementation use different vocabularies. Translations for data_access protocols have been expanded.
=> Added more translations on data_access to handle CMEMS catalogue

doc/ch04-md-contrvocabs.adoc, thesauri/mmd-vocabulary.ttl, thesauri/mmd-vocabulary.xml, xsd/mmd.xsd
=> add SESS2022 to keywords in doc, thesauri and schema

doc/ch01-introduction.adoc, doc/ch04-md-contrvocabs.adoc, tests/data/precipitation_amount_st_92350.xml, tests/data/precipitation_amount_st_92350_EMPTY_ATTR.xml, tests/data/precipitation_amount_st_92350_NO_LANG_ATTR.xml, thesauri/mmd-vocabulary.ttl, thesauri/mmd-vocabulary.xml, xslt/mmd-to-inspire.xsl, xslt/mmd-to-iso2.xsl, xslt/mmd-to-wmo.xsl, xslt/mmdv2-to-mmdv3.xsl
Update of vocabulary reference in mmd specifications - close #208 
@mortenwh you should update this in other related documentation outside of the mmd repository.
=> update cf standard name vocabulary reference to nerc vocabulary

xsd/mmd_strict.xsd
=> project short name no longer mandatory

xsd/mmd_strict.xsd
=> #219: add option

xslt/mmd-to-inspire.xsl
I've added creation date if present, updated the keyword vocabulary and added the landing page to transferOption to the inspire profile translation.
=> improve inspire profile

doc/ch04-md-contrvocabs.adoc, thesauri/mmd-vocabulary.ttl, thesauri/mmd-vocabulary.xml
=> add noaa-21 platform in vocabulary and documentation

thesauri/mmd-vocabulary.xml
=> fix closing tag typo in mmd-vocabulary.xml

xslt/dif-to-mmd.xsl
This is a major revision of the dif to mmd, covering both 9 and 10 version.
The following has been implemented:
- dataset_status: now both Data_Set_Progress (dif9) and Dataset_Progress (dif10) are parsed and mapped to mmd vocabulary
- last_metadata_update: a better handling of creation and revision dates.
i) It now handles the possibility (as we have in many records) that neither creation nor revision dates are provided
ii) If both revision and creation are provided, they are both translated, while before the creation date was translated only if the revision was missing (closes #221 )
- keywords (vocabulary="None"): this part is created now only if Keyword or Ancillary_Keyword are present. Ancillary_Keyword (dif10) was missing
- dataset_language: both Data_Set_Language (dif9) and …
=> major update of dif-to-mmd

xslt/mmd-to-geonorge.xsl
Added extra check to test if OGC WMS resource contains getcapabilities string on satellite data
Closes #249
=> mmd-to-geonorge: don't add getcapabilities if its already there

doc/ch04-md-contrvocabs.adoc, thesauri/mmd-vocabulary.ttl, thesauri/mmd-vocabulary.xml, xsd/mmd.xsd, xsd/mmd_strict.xsd
Support for filtering of data going towards genorge and additional tags for KSS. This Closes #251
=> adding GEONOR and KSS to collection keywords

.github/workflows/coverage.yml, .github/workflows/make-doc.yml, .github/workflows/unittests.yml, doc/ch04-md-contrvocabs.adoc, thesauri/mmd-vocabulary.ttl, thesauri/mmd-vocabulary.xml
=> add Envisat and ASAR to vocabulary

doc/ch04-md-contrvocabs.adoc, thesauri/mmd-vocabulary.ttl, thesauri/mmd-vocabulary.xml
added noaa-15 to thresauri files and to the adoc documentation.
=> add noaa-15 to platform vocabulary

doc/ch04-md-contrvocabs.adoc, thesauri/mmd-vocabulary.ttl, thesauri/mmd-vocabulary.xml, xsd/mmd.xsd, xsd/mmd_strict.xsd
Added collection POLARIN. 
Check if it is maybe more appropriate to have as description "Datasets **related to the** POLARIN Project." instead of "Datasets from the POLARIN Project.", if so I can change it.
=> add POLARIN collection keyword

doc/ch04-md-contrvocabs.adoc, thesauri/mmd-vocabulary.ttl, thesauri/mmd-vocabulary.xml
This PR should cover addition of new Sentinel platforms, new instruments as well as it includes updates of old records with new relations between platforms and instruments. Closes #277 #278 #279
=> add new platforms and instruments and update old entries
