xslt/mmd-to-datacite.xsl
We need to revise this, but for now it matches the PI with the mandatory creator element.
=> add mapping betweeing Personnel with role Investigator and creator name

xslt/mdform-to-mmd.xsl
I have added the possibility of adding other roles (technical contact and metadata author) to the metadata-form. I have also added the dataset_citation elements. All fields are not translated to the new mmd structure.
=> extract other roles and dataset citation from metadata-form

doc/ch02-md-elements-last_metadata_update.adoc
In order to fully support requirements of e.g. DataCite we need to capture creation date etc for metadata records. The following suggested structure allows capturing both creation as well as subsequent updates to the metadata records. Please review and comment or merge.
=> Modified the structure of last_metadata_update

doc/ch02-md-elements-data_center.adoc, input-examples/foo.mmd, xsd/mmd.xsd, xsd/solr-mmd-l1.xml, xsd/solr-mmd-l2.xml, xslt/dif-to-mmd.xsl, xslt/mmd-to-dif.xsl, xslt/mmd-to-dif10.xsl
remove dataset_id: in documentation, mmd input example, mmd schema and solr schema. Commented out in the xlst dif files, as it should be updated when alternated_identifier has been defined (marked as TODO). 
This relates to #16.
=> remove dataset_id 

xslt/mmdv2-to-mmdv3.xsl
This is translating from the previous version of MMD and the new, current release. 
There are some open issues: 
- translation of the old "last_metadata_update" to a new record is now skipped, as we do not know the type. A new entry "Minor modification" with a note on the version upgrade is created with the current datetime. 
- A mapping of use_constraint is in place, but some records that did not use controlled vocabulary are now not translated (see #103  for possible fix)
-  For NBS products timeliness entry cannot be created from old records as it is not present. If needed, the record must be appended separately
- the old "reference" record is not translated, some records might be translated into related_information, but is should be checked depending on type of entry (not structured).
=> add xslt file to translate old mmd records to new mmd records.

doc/ch01-introduction.adoc, doc/ch02-md-elements-keywords.adoc, doc/ch04-md-contrvocabs.adoc, tests/test_schemas.py, xsd/mmd_strict.xsd
This PR would upgrade the description of the keywords vocabulary attribute linking to suggested vocabulary that should be used now for reference. The schema for the internal mmd_strict.xsd is also updated. 
My suggestion would be to integrate this now and do a second upgrade of the xslt folder (opening a new issue) when we can polish the mmd records with the new list of vocabularies to avoid having to support both old (GCMD) and new (GCMDSK) nomenclature.
=> controlled vocabulary for keywords attribute

doc/ch04-md-contrvocabs.adoc, thesauri/mmd-vocabulary.ttl, thesauri/mmd-vocabulary.xml, xsd/mmd.xsd, xslt/dif-to-mmd.xsl, xslt/ecmwf-iso-to-mmd.xsl, xslt/iso-to-mmd.xsl, xslt/mmd-to-dif.xsl, xslt/mmd-to-dif10.xsl, xslt/mmd-to-iso.xsl, xslt/mmd-to-iso2.xsl
These are the main changes: 
- doc: added "Not available" for dataset_production_status (updated iso mapping tables), iso_topic_category, operational_status and activity_type. Added "None" for vocabulary attribute.
- thesauri: added "Not available" for the above mentioned entries, with skos note for change.
- mmd.xsd: added values in list.
- dif-to-mmd: added "Not available" if Data_Set_Progress or ISO_Topic_Category are not provided
- ecmwf-iso-to-mmd: added "Not available" if gmd:status and gmd:MD_TopicCategoryCode are not provided. Fix vocabulary attribute from none to None
- iso-to-mmd: added "Not available" if gmd:status and gmd:MD_TopicCategoryCode are not provided. Fix vocabulary attribute from none to None and gcmd to GCMDSK.
- mmd-to-dif: do not map Data_Set_Progress and …
=> Addition of Not available entry in controlled vocabulary

doc/ch04-md-contrvocabs.adoc, thesauri/mmd-vocabulary.ttl, thesauri/mmd-vocabulary.xml, xsd/mmd.xsd, xsd/mmd_strict.xsd
This is a minor PR to add a missing collection tag for the SIOS InfraNor data. Changes are included in the documentation, the thesauri and the schemas. Closes #190
=> Add SIOSIN to collection tag

doc/ch04-md-contrvocabs.adoc, thesauri/mmd-vocabulary.ttl, thesauri/mmd-vocabulary.xml, xsd/mmd.xsd, xsd/mmd_strict.xsd
AeN was missing from the documentation and controlled vocabularies. close #211
=> add AeN collection keyword

thesauri/mmd-vocabulary.ttl, thesauri/mmd-vocabulary.xml, xslt/mmd-to-geonorge.xsl
- Added Spatial Representation to vocabulary. 
- Updated mmd-to-geonorge to pick up only compliant values of spatial representation (only vector and grid are valid entries, other mmd supported entries are only internal)
- Update mmd-to-geonorge publication date (this is not part of #226 , but while testing the changes I've noticed that publication_date is the xsd is not forced to be a xs:date, only xs:string, documentation says we expect a date (not datetime), but several mmd records are not following this and provide datetime instead)
Closes #226
=> add spatial representation in thesauri, update xslt to genorge

xslt/iso-to-mmd.xsl
I've added two different namespaces for gml and gml32 and added an OR statement to match the different URIs from the namespaces. Tested locally it seems to work smoothly for both cases.
=> add support for both gml and gml 3.2 in iso-to-mmd

doc/ch04-md-contrvocabs.adoc, thesauri/mmd-vocabulary.ttl, thesauri/mmd-vocabulary.xml, xsd/mmd.xsd, xsd/mmd_strict.xsd, xslt/mmd-to-geonorge.xsl
The changes are the following: 
- added CC-BY-3.0 in the documentation for controlled vocabularies
- added CC-BY-3.0 in the thesauri files
- added CC-BY-3.0 in the schemas (mmd and mmd_strict)
- added translation to genorge code in mmd-to-genorge
Closes #229
=> Add support for CC-BY-3.0

xslt/dif-to-mmd.xsl
NPI releases DIF10 records with an appearance like:
'''
<Metadata_Dates>
<Metadata_Creation>2023-12-04T17:11:12Z</Metadata_Creation>
<Metadata_Last_Revision>Not provided</Metadata_Last_Revision>
<Data_Creation>Not provided</Data_Creation>
<Data_Last_Revision>Not provided</Data_Last_Revision>
</Metadata_Dates>
'''
This cause issues on ingestion side for MMD records which have dates of type "Not provided". A hack to prevent such strings to pass through has been added. Full datetime validation would be easier with XSLT 2, but for now we are using XSLT 1.
=> Added a test to handle DIF10 records from NPI

doc/ch04-md-contrvocabs.adoc, thesauri/mmd-vocabulary.ttl, thesauri/mmd-vocabulary.xml, xsd/mmd.xsd, xsd/mmd_strict.xsd
Added keywords in the documentation, schemas and vocabularies. closes #240
=> add TONE and NySMAC collections

thesauri/mmd-vocabulary.ttl, thesauri/mmd-vocabulary.xml, xslt/dif-to-mmd.xsl
1. I've reviewed the license vocabulary, adding altLabel to support translations from external resources. 
2. Updated CC0 which had a faulty reference
3. Included Use_Constraint to dif-to-mmd (this now checks for prefLabel, e.g. CC-BY-4.0, but also for altLabel, e.g. CC BY 4.0, and creates the appropriate identifier/resources in mmd). Any other non empty case will be put into license_text. 
This closes #246 and #247 
Note: more altLabel can be added in the future if harvested records provide some other consistent strings.
=> minor changes in license vocabulary and inclusion of Use_Constraint translation in dif-to-mmd

thesauri/mmd-vocabulary.ttl, thesauri/mmd-vocabulary.xml, xslt/mmd-to-NOiso.xsl
Closes #252 
- Added Organisation mapping to vocab (to be used to provide Norwegian names to genorge)
- Added dedicated mmd-to-Noiso to generalise mmd-to-genorge
=> add organisations to vocab and add xslt to Norsk Profil ISO

tests/test_schemas.py
These two tests should ensure that the xml and ttl files in the thesauri folder are not faulty. Closes #255
=> add test on thesauri files

xslt/mmd-to-NOiso.xsl
This PR removes the repetition of individual and organisation in CI contact if mmd:name and mmd:organisation are the same, it also has a more flexible handling of Norwegian organisation names. 
Changes are limited to mmd-to-NOiso.
=> creating better handling of organisation in NOiso xslt

xslt/iso-to-mmd.xsl
This PR should fix project extraction for iso-to-mmd.xsl (closes #266 ):
- it looks for codeList and handle also multiple entries
In addition:
- There is some reshuffle of elements to fit xsd schema 
- Fix iso_topic_category (it was not creating multiple fields if more several entries were provided)
- It adds srsName for geographic extent (which was missing)
- It adds T12:00:00Z for datetime when time is not provided (which was missing)
=> fix project translation and minor changes

doc/ch04-md-contrvocabs.adoc, thesauri/mmd-vocabulary.ttl, thesauri/mmd-vocabulary.xml, xsd/mmd.xsd, xsd/mmd_strict.xsd, xslt/mmd-to-dif.xsl, xslt/mmd-to-dif10.xsl
This PR closes #207 
The purpose is to find a place to keep the urls from application servers (e.g. thredds) while moving these resources from the type "dataset landing page". This new element will host application server urls from data files and virtual data collection (e.g. catalogs). 
- it introduces a new type in the vocabulary
- it updates documentation
- it updates xsd schemas
- it extends translation mmd-to-dif(10). 
In addition a small bug fix in the vocabulary is done for broader/broadMatch on Data Paper and Scientific Publication
=> add Data server landing page as related information type

xslt/iso-to-mmd.xsl
From iso valid entries:  "vector", "grid", "tin" or "textTable", only the first two can be matched to mmd list. 
Closes #289
=> add spatial_representation parsing in iso-to-mmd
